//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompletionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompletionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.CompletionResources", typeof(CompletionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regulator will only review your application after you&apos;ve made payment..
        /// </summary>
        public static string AfterPayment {
            get {
                return ResourceManager.GetString("AfterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount due.
        /// </summary>
        public static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to the Environment Agency.
        /// </summary>
        public static string ApplicationSubmittedEngland {
            get {
                return ResourceManager.GetString("ApplicationSubmittedEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to Northern Ireland Environment Agency.
        /// </summary>
        public static string ApplicationSubmittedIreland {
            get {
                return ResourceManager.GetString("ApplicationSubmittedIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to the Scotish Environment Protection Agency.
        /// </summary>
        public static string ApplicationSubmittedScotland {
            get {
                return ResourceManager.GetString("ApplicationSubmittedScotland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these details to make payment:
        ///
        ///Company name: Environment Agency 
        ///Bank RBS/NatWest 
        ///Address London Corporate Service Centre, CPB Services, 2nd Floor, 280 Bishopsgate, London EC2M 4RB 
        ///Sort code 60-70-80 
        ///Account number 10014411 
        ///Account name EA RECEIPTS 
        ///Payment reference number: &lt;Same as reference number in green confirmation box above&gt;
        ///
        ///Progressive reveal title: Other ways to pay 
        ///To discuss paying by other methods please contact the Environment Agency
        ///
        ///
        ///
        ///Email: packaging@environment-ag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BankTransferDetails {
            get {
                return ResourceManager.GetString("BankTransferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay.
        /// </summary>
        public static string HowToPay {
            get {
                return ResourceManager.GetString("HowToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Completion.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Completion.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by bank transfer.
        /// </summary>
        public static string PayByBankTransfer {
            get {
                return ResourceManager.GetString("PayByBankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay online.
        /// </summary>
        public static string PayOnline {
            get {
                return ResourceManager.GetString("PayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.gov.uk.
        /// </summary>
        public static string PayOnlineLink {
            get {
                return ResourceManager.GetString("PayOnlineLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can pay online using GOV.UK Pay.
        /// </summary>
        public static string PayOnlineNotice {
            get {
                return ResourceManager.GetString("PayOnlineNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
    }
}
