//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CompletionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompletionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.CompletionResources", typeof(CompletionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account name: DAERA.
        /// </summary>
        public static string AccountNameIreland {
            get {
                return ResourceManager.GetString("AccountNameIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regulator will only review your application after you&apos;ve made payment..
        /// </summary>
        public static string AfterPayment {
            get {
                return ResourceManager.GetString("AfterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount due.
        /// </summary>
        public static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to the Environment Agency.
        /// </summary>
        public static string ApplicationSubmittedEngland {
            get {
                return ResourceManager.GetString("ApplicationSubmittedEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to Northern Ireland Environment Agency.
        /// </summary>
        public static string ApplicationSubmittedIreland {
            get {
                return ResourceManager.GetString("ApplicationSubmittedIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to the Scotish Environment Protection Agency.
        /// </summary>
        public static string ApplicationSubmittedScotland {
            get {
                return ResourceManager.GetString("ApplicationSubmittedScotland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted to Natual Resources Wales.
        /// </summary>
        public static string ApplicationSubmittedWales {
            get {
                return ResourceManager.GetString("ApplicationSubmittedWales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACS remittanace: billtocash@accountnl.gov.uk.
        /// </summary>
        public static string BACSIreland {
            get {
                return ResourceManager.GetString("BACSIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account number: 61253506.
        /// </summary>
        public static string BankAccountNumberIreland {
            get {
                return ResourceManager.GetString("BankAccountNumberIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bank: Danske bank. PO BOX 183 Donegail Square West. Belfast. BT1 6JS.
        /// </summary>
        public static string BankNameIrelreland {
            get {
                return ResourceManager.GetString("BankNameIrelreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these details to make payment:
        ///
        ///Company name: Environment Agency 
        ///Bank RBS/NatWest 
        ///Address London Corporate Service Centre, CPB Services, 2nd Floor, 280 Bishopsgate, London EC2M 4RB 
        ///Sort code 60-70-80 
        ///Account number 10014411 
        ///Account name EA RECEIPTS 
        ///Payment reference number: &lt;Same as reference number in green confirmation box above&gt;
        ///
        ///Progressive reveal title: Other ways to pay 
        ///To discuss paying by other methods please contact the Environment Agency
        ///
        ///
        ///
        ///Email: packaging@environment-ag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BankTransferDetails {
            get {
                return ResourceManager.GetString("BankTransferDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort code: 95-01-21.
        /// </summary>
        public static string BnakSortCodeIreland {
            get {
                return ResourceManager.GetString("BnakSortCodeIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name EA RECEIPTS.
        /// </summary>
        public static string EnglandAccountName {
            get {
                return ResourceManager.GetString("EnglandAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number 10014411.
        /// </summary>
        public static string EnglandAccountNumber {
            get {
                return ResourceManager.GetString("EnglandAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address London Corporate Service Centre, CPB Services, 2nd Floor, 280 Bishopsgate, London EC2M 4RB.
        /// </summary>
        public static string EnglandAddress {
            get {
                return ResourceManager.GetString("EnglandAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank RBS/NatWest.
        /// </summary>
        public static string EnglandBnakName {
            get {
                return ResourceManager.GetString("EnglandBnakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort code 60-70-80.
        /// </summary>
        public static string EnglandBnakSortCode {
            get {
                return ResourceManager.GetString("EnglandBnakSortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name: Environment Agency.
        /// </summary>
        public static string EnglandCompanyName {
            get {
                return ResourceManager.GetString("EnglandCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay.
        /// </summary>
        public static string HowToPay {
            get {
                return ResourceManager.GetString("HowToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other ways to pay.
        /// </summary>
        public static string OtherwaysToPay {
            get {
                return ResourceManager.GetString("OtherwaysToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: packaging@environment-agency.gov.uk.
        /// </summary>
        public static string OtherwaysToPayEmail {
            get {
                return ResourceManager.GetString("OtherwaysToPayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To discuss paying by other methods please contact the Environment Agency.
        /// </summary>
        public static string OtherwaysToPayEngland {
            get {
                return ResourceManager.GetString("OtherwaysToPayEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To discuss paying by other methods please contact the Northern Ireland Environment Agency.
        /// </summary>
        public static string OtherwaysToPayIreland {
            get {
                return ResourceManager.GetString("OtherwaysToPayIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone: 03708 506506.
        /// </summary>
        public static string OtherwaysToPayPhoneEngland {
            get {
                return ResourceManager.GetString("OtherwaysToPayPhoneEngland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone: 028 9058 9338.
        /// </summary>
        public static string OtherwaysToPayPhoneIreland {
            get {
                return ResourceManager.GetString("OtherwaysToPayPhoneIreland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone: 0300 065 3000.
        /// </summary>
        public static string OtherwaysToPayPhoneWales {
            get {
                return ResourceManager.GetString("OtherwaysToPayPhoneWales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To discuss paying by other methods please contact the Natural Resources Wales.
        /// </summary>
        public static string OtherWaysToPayWales {
            get {
                return ResourceManager.GetString("OtherWaysToPayWales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Completion.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accreditation Completion.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay by bank transfer.
        /// </summary>
        public static string PayByBankTransfer {
            get {
                return ResourceManager.GetString("PayByBankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment reference number:.
        /// </summary>
        public static string PaymentReference {
            get {
                return ResourceManager.GetString("PaymentReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay online.
        /// </summary>
        public static string PayOnline {
            get {
                return ResourceManager.GetString("PayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.gov.uk.
        /// </summary>
        public static string PayOnlineLink {
            get {
                return ResourceManager.GetString("PayOnlineLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can pay online using GOV.UK Pay.
        /// </summary>
        public static string PayOnlineNotice {
            get {
                return ResourceManager.GetString("PayOnlineNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact the Scottish Environmental Protection Agency for payment details..
        /// </summary>
        public static string ScotlandContact {
            get {
                return ResourceManager.GetString("ScotlandContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: producer.responsibility@sepa.org.uk.
        /// </summary>
        public static string ScotlandEmail {
            get {
                return ResourceManager.GetString("ScotlandEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone: 01786 457700.
        /// </summary>
        public static string ScotlandPhone {
            get {
                return ResourceManager.GetString("ScotlandPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use these details to make payment.
        /// </summary>
        public static string UseDetails {
            get {
                return ResourceManager.GetString("UseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company address: Income department, PO BOX 663, Cardiff, CF24 0TP.
        /// </summary>
        public static string WalesAddress {
            get {
                return ResourceManager.GetString("WalesAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank: RBS, National Westminster bank plc, 2 ½ Devonshire Square, London, EC2M 4BA.
        /// </summary>
        public static string WalesBank {
            get {
                return ResourceManager.GetString("WalesBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number: 10014438.
        /// </summary>
        public static string WalesBankAccountNumber {
            get {
                return ResourceManager.GetString("WalesBankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort code: 60-70-80.
        /// </summary>
        public static string WalesBankSortCode {
            get {
                return ResourceManager.GetString("WalesBankSortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name: Natural Resources Wales.
        /// </summary>
        public static string WalesCompanyName {
            get {
                return ResourceManager.GetString("WalesCompanyName", resourceCulture);
            }
        }
    }
}
