//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileUploadResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.FileUploadResources", typeof(FileUploadResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow charts.
        /// </summary>
        public static string FlowChart_Title {
            get {
                return ResourceManager.GetString("FlowChart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file must be:.
        /// </summary>
        public static string Hint_Header {
            get {
                return ResourceManager.GetString("Hint_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up to 20Mb.
        /// </summary>
        public static string Hint_Item1 {
            get {
                return ResourceManager.GetString("Hint_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one of the following file types: PDF, DOC, DOCX, XLS, CSV, PNG, TIF, JPG, MSG.
        /// </summary>
        public static string Hint_Item2 {
            get {
                return ResourceManager.GetString("Hint_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not password protected.
        /// </summary>
        public static string Hint_Item3 {
            get {
                return ResourceManager.GetString("Hint_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of plants and equipment used to reprocess this material.
        /// </summary>
        public static string PlantsAndEquipment_Title {
            get {
                return ResourceManager.GetString("PlantsAndEquipment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording systems.
        /// </summary>
        public static string RecordingSystems_Title {
            get {
                return ResourceManager.GetString("RecordingSystems_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling and inspection plan.
        /// </summary>
        public static string SamplingAndInspection_Title {
            get {
                return ResourceManager.GetString("SamplingAndInspection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload supporting documents.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
