//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaterialOutputsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialOutputsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.MaterialOutputsResources", typeof(MaterialOutputsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter waste material outputs before moving.
        /// </summary>
        public static string ContaminentsBlank {
            get {
                return ResourceManager.GetString("ContaminentsBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contaminents.
        /// </summary>
        public static string ContaminentsField {
            get {
                return ResourceManager.GetString("ContaminentsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tonnage of contaminents removed from the materials during reprocessing, including non-recyclable components or impurities..
        /// </summary>
        public static string ContaminentsHint {
            get {
                return ResourceManager.GetString("ContaminentsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter waste material outputs before moving.
        /// </summary>
        public static string MaterialsNotProcessedBlank {
            get {
                return ResourceManager.GetString("MaterialsNotProcessedBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials not processed on site.
        /// </summary>
        public static string MaterialsNotProcessedField {
            get {
                return ResourceManager.GetString("MaterialsNotProcessedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tonnage of materials received but not processed at your site, including materials sent to other sites for processing..
        /// </summary>
        public static string NotProcessedOnSiteHint {
            get {
                return ResourceManager.GetString("NotProcessedOnSiteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter waste material outputs before moving.
        /// </summary>
        public static string ProcessLossBlank {
            get {
                return ResourceManager.GetString("ProcessLossBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Loss.
        /// </summary>
        public static string ProcessLossField {
            get {
                return ResourceManager.GetString("ProcessLossField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tonnage of material lost due to processing, such as material degradation or waste..
        /// </summary>
        public static string ProcessLossHint {
            get {
                return ResourceManager.GetString("ProcessLossHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your waste material outputs for the last calendar year.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
