//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NpwdAccrNumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NpwdAccrNumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.NpwdAccrNumResources", typeof(NpwdAccrNumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your NPWD number in the correct format.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPWD number must only includes letters a to z, or numbers.
        /// </summary>
        public static string ErrorMessageInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your accreditation number for:.
        /// </summary>
        public static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It starts with 2 letters, followed by up to 10 numbers..
        /// </summary>
        public static string HintText {
            get {
                return ResourceManager.GetString("HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public register (opens in a new tab).
        /// </summary>
        public static string LinkText {
            get {
                return ResourceManager.GetString("LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find it on the.
        /// </summary>
        public static string P1 {
            get {
                return ResourceManager.GetString("P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your NPWD accreditation number.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your NPWD accreditation number.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
