//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskListResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskListResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.TaskListResources", typeof(TaskListResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the material.
        /// </summary>
        public static string AboutMaterial {
            get {
                return ResourceManager.GetString("AboutMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overseas reprocessing sites.
        /// </summary>
        public static string OverseasHeader {
            get {
                return ResourceManager.GetString("OverseasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be started after completing &apos;About the waste you export&apos;..
        /// </summary>
        public static string OverseasHintLink {
            get {
                return ResourceManager.GetString("OverseasHintLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overseas reprocessing sites .
        /// </summary>
        public static string OverseasLink {
            get {
                return ResourceManager.GetString("OverseasLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your application task list. You can save your progress and come back to it at any time..
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for accreditation as an exporter.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your business plan .
        /// </summary>
        public static string UploadBusinessPlan {
            get {
                return ResourceManager.GetString("UploadBusinessPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload sampling and inspection plan and recording system for this material.
        /// </summary>
        public static string UploadInspectionPlan {
            get {
                return ResourceManager.GetString("UploadInspectionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the packaging waste you export .
        /// </summary>
        public static string WasteExportHeader {
            get {
                return ResourceManager.GetString("WasteExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you’ve completed one material you can add more materials. You can upload documents after you&apos;ve chosen a material. .
        /// </summary>
        public static string WasteExportTitle {
            get {
                return ResourceManager.GetString("WasteExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste licences, PERN and business plan .
        /// </summary>
        public static string WasteLicencesHeading {
            get {
                return ResourceManager.GetString("WasteLicencesHeading", resourceCulture);
            }
        }
    }
}
