//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WasteLicensesAndPermitsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WasteLicensesAndPermitsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.WasteLicensesAndPermitsResources", typeof(WasteLicensesAndPermitsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste carrier, broker or dealer registration number.
        /// </summary>
        public static string DealerRegistrationNumber {
            get {
                return ResourceManager.GetString("DealerRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration numberr not in range.
        /// </summary>
        public static string DealerRegistrationNumberNotInRange {
            get {
                return ResourceManager.GetString("DealerRegistrationNumberNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge consent number.
        /// </summary>
        public static string DischargeConstentNumber {
            get {
                return ResourceManager.GetString("DischargeConstentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management license or environment permit number.
        /// </summary>
        public static string EnvironmentalPermitNumber {
            get {
                return ResourceManager.GetString("EnvironmentalPermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if you do not have one..
        /// </summary>
        public static string LeaveBlank {
            get {
                return ResourceManager.GetString("LeaveBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste carrier, broker or dealer registration number is missing.
        /// </summary>
        public static string MissingDealerRegistrationNumberNumber {
            get {
                return ResourceManager.GetString("MissingDealerRegistrationNumberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing discharge constent number.
        /// </summary>
        public static string MissingDischargeConstentNumber {
            get {
                return ResourceManager.GetString("MissingDischargeConstentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Number is missing.
        /// </summary>
        public static string MissingEnvironmentalPermitNumber {
            get {
                return ResourceManager.GetString("MissingEnvironmentalPermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing actitivy reference number.
        /// </summary>
        public static string MissingPartAActivityReferenceNumber {
            get {
                return ResourceManager.GetString("MissingPartAActivityReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing activity number.
        /// </summary>
        public static string MissingPartBActivityReferenceNumber {
            get {
                return ResourceManager.GetString("MissingPartBActivityReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number is missing.
        /// </summary>
        public static string MissingRegistrationNumber {
            get {
                return ResourceManager.GetString("MissingRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Licenses And Permits.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPC &apos;Part B or C&apos; or non-waste EPR &apos;Part A2 or B&apos; activity reference number .
        /// </summary>
        public static string PartAActivityReferenceNumber {
            get {
                return ResourceManager.GetString("PartAActivityReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPC &apos;Part A&apos; or non-waste EPR &apos;Part A1&apos; activity number.
        /// </summary>
        public static string PartBActivityReferenceNumber {
            get {
                return ResourceManager.GetString("PartBActivityReferenceNumber", resourceCulture);
            }
        }
    }
}
