//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPR.Accreditation.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WasteLicencesAndPermitsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WasteLicencesAndPermitsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPR.Accreditation.Portal.Resources.WasteLicencesAndPermitsResources", typeof(WasteLicencesAndPermitsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste carrier, broker or dealer registration number.
        /// </summary>
        public static string DealerRegistrationNumber {
            get {
                return ResourceManager.GetString("DealerRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge consent number.
        /// </summary>
        public static string DischargeConsentNumber {
            get {
                return ResourceManager.GetString("DischargeConsentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the reference numbers for the licences and permits you have..
        /// </summary>
        public static string EnterRefNumText {
            get {
                return ResourceManager.GetString("EnterRefNumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste management licence or environmental permit number.
        /// </summary>
        public static string EnvironmentalPermitNumber {
            get {
                return ResourceManager.GetString("EnvironmentalPermitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number must include letters, numbers  or &apos;/&apos; only.
        /// </summary>
        public static string ErrorMessageInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number must not exceed 20 characters.
        /// </summary>
        public static string ErrorMessageTooLong {
            get {
                return ResourceManager.GetString("ErrorMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if you do not have one..
        /// </summary>
        public static string LeaveBlank {
            get {
                return ResourceManager.GetString("LeaveBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste licences and permits.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Licenses And Permits.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPC ‘Part A’ or non-waste EPR ‘Part A1’ activity reference number.
        /// </summary>
        public static string PartAReferenceNumber {
            get {
                return ResourceManager.GetString("PartAReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPC ‘Part B or C’ or non-waste EPR ‘Part A2 or B’ activity reference number.
        /// </summary>
        public static string PartBReferenceNumber {
            get {
                return ResourceManager.GetString("PartBReferenceNumber", resourceCulture);
            }
        }
    }
}
