<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cb5be479-98ed-40d6-91a5-7f4a9e8d3ee8</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ClientApp\js\pages\**" />
    <Content Remove="ClientApp\js\pages\**" />
    <EmbeddedResource Remove="ClientApp\js\pages\**" />
    <None Remove="ClientApp\js\pages\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="EPR.Common.Authorization" Version="1.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Localization" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.25" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.3" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.17.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\AddressResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AddressResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\LegalDocumentsAddressResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LegalDocumentsAddressResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\NpwdAccrNumResources.cy-GB.Designer.cs">
      <DependentUpon>NpwdAccrNumResources.cy-GB.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\NpwdAccrNumResources.Designer.cs">
      <DependentUpon>NpwdAccrNumResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\HasNpwdAccrNumResources.cy-GB.Designer.cs">
      <DependentUpon>HasNpwdAccrNumResources.cy-GB.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\MaterialOutputsEstimatedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MaterialOutputsEstimatedResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MaterialOutputsLastYearResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MaterialOutputsLastYearResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\NonWasteInputEstimatedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NonWasteInputEstimatedResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\NonWasteInputLastYearResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NonWasteInputLastYearResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MaterialWasteOutputsEstimatedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MaterialWasteOutputsEstimatedResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MaterialWasteOutputsLastYearResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MaterialWasteOutputsLastYearResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\OverseasReprocessorResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OverseasReprocessorResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\HasNpwdAccrNumResources.Designer.cs">
      <DependentUpon>HasNpwdAccrNumResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\PrnTonnesPlannedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PrnTonnesPlannedResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ProductsProducedLastYearResources.Designer.cs">
      <DependentUpon>ProductsProducedLastYearResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ProductsProducedEstimatedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProductsProducedEstimatedResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ReprocessorDetailsResources.Designer.cs">
      <DependentUpon>ReprocessorDetailsResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
	  <Compile Update="Resources\OverseasSiteOutputsResources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>OverseasSiteOutputsResources.resx</DependentUpon>
	  </Compile>
    <Compile Update="Resources\SiteAddressResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SiteAddressResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\TaskListSiteResources.Designer.cs">
      <DependentUpon>TaskListSiteResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ExemptionReferencesResources.Designer.cs">
      <DependentUpon>ExemptionReferencesResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\TaskListResources.Designer.cs">
      <DependentUpon>TaskListResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\WasteDescriptionCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WasteDescriptionCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\WasteLastYearResources.Designer.cs">
      <DependentUpon>WasteLastYearResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\PermitExemptionResources.Designer.cs">
      <DependentUpon>PermitExemptionResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\GovFrontEndTextOverrideResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GovFrontEndTextOverrideResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MasterResources.Designer.cs">
      <DependentUpon>MasterResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\MaterialNamesResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MaterialNamesResource.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\OperatorTypeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OperatorTypeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\PhaseBannerResources.Designer.cs">
      <DependentUpon>PhaseBannerResources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\ApplicationSavedResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ApplicationSavedResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\WasteSourceResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WasteSourceResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\WasteLicencesAndPermitsResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WasteLicencesAndPermitsResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\AddressResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AddressResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\AddressResources.cy-GB.resx">
      <LastGenOutput>ApplicationSavedResources - Copy.cy-GB.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\LegalDocumentsAddressResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LegalDocumentsAddressResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\NpwdAccrNumResources.cy-GB.resx">
      <LastGenOutput>NpwdAccrNumResources.cy-GB.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\NpwdAccrNumResources.resx">
      <LastGenOutput>NpwdAccrNumResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\HasNpwdAccrNumResources.cy-GB.resx">
      <LastGenOutput>HasNpwdAccrNumResources.cy-GB.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialOutputsEstimatedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialOutputsEstimatedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialOutputsLastYearResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialOutputsLastYearResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\NonWasteInputEstimatedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NonWasteInputEstimatedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\NonWasteInputLastYearResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NonWasteInputLastYearResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsEstimatedResources.cy-GB.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsEstimatedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialWasteOutputsEstimatedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsLastYearResources.cy-GB.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsLastYearResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialWasteOutputsLastYearResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\OverseasReprocessorResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OverseasReprocessorResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\HasNpwdAccrNumResources.resx">
      <LastGenOutput>HasNpwdAccrNumResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PrnTonnesPlannedResources.cy-GB.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PrnTonnesPlannedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PrnTonnesPlannedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProductsProducedLastYearResources.resx">
      <LastGenOutput>ProductsProducedLastYearResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProductsProducedEstimatedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProductsProducedEstimatedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsEstimatedResources.cy-GB.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsEstimatedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialWasteOutputsEstimatedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsLastYearResources.cy-GB.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialWasteOutputsLastYearResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialWasteOutputsLastYearResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\OverseasSiteOutputsResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OverseasSiteOutputsResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ReprocessorDetailsResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ReprocessorDetailsResources.resx">
      <LastGenOutput>ReprocessorDetailsResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SiteAddressResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SiteAddressResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SiteAddressResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TaskListSiteResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TaskListSiteResources.resx">
      <LastGenOutput>TaskListSiteResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ExemptionReferencesResources.resx">
      <LastGenOutput>ExemptionReferencesResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TaskListResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\TaskListResources.resx">
      <LastGenOutput>TaskListResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\WasteDescriptionCodeResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WasteDescriptionCodeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\WasteLastYearResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\WasteLastYearResources.resx">
      <LastGenOutput>WasteLastYearResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PermitExemptionResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PermitExemptionResources.resx">
      <LastGenOutput>PermitExemptionResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ApplicationSavedResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\GovFrontEndTextOverrideResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>GovFrontEndTextOverrideResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MasterResources.cy-GB.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MasterResources.resx">
      <LastGenOutput>MasterResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MaterialNamesResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MaterialNamesResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\OperatorTypeResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OperatorTypeResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PhaseBannerResources.cy-GB.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\PhaseBannerResources.resx">
      <LastGenOutput>PhaseBannerResources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ApplicationSavedResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ApplicationSavedResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\WasteSourceResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WasteSourceResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\WasteLicencesAndPermitsResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>WasteLicencesAndPermitsResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPR.Accreditation.Portal.Common\EPR.Accreditation.Portal.Common.csproj" />
  </ItemGroup>

</Project>
