variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'epraccreditationfrontend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'epraccreditationfrontendrepository'
  serviceName: 'prdrwdwebwa1420'
