variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'epraccreditationfrontend'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'epraccreditationfrontendrepository'
- name: serviceName
  value: 'prdrwdwebwa1420'
